### PR TITLE
Dropped CircleCI config

### PR DESCRIPTION
**Pull request by carterqw2**
Removing CircleCI config in favor of Github Actions.

### CODE REVIEW

**Comment by aaronmgdr** [comment]
gotta take off circle ci as a requirment for merging

**Review by rkachowski — APPROVED** [review]
Did we ever use CircleCI? it seems upstream has the same config - if that's the case we could also remove related shell scripts and resources referenced in `config.yml`

**Comment by carterqw2** [comment]
> Did we ever use CircleCI? it seems upstream has the same config - if that's the case we could also remove related shell scripts and resources referenced in `config.yml`

Blockscout used to use CircleCI but they switched to Github Actions eventually. Can't really drop the bash script as the GA config relies on it as well. Or do you mean something else?

**Comment by rkachowski** [comment]
>  Can't really drop the bash script as the GA config relies on it as well. Or do you mean something else?

Ah I didn't look hard enough at the config and just saw some `.sh` file referenced, I had meant the shell scripts in `/rel` as we are no longer using `mix release` in an automated form.

**Pull request merged**
