### PR TITLE
Add tracing by block logic for geth

### PR DESCRIPTION
**Pull request by carterqw2**
### Description

Previously blockscout when using geth (unlike other clients) would trace transactions one by one, using the `debug_traceTransaction` RPC endpoint, that would result in an excessive number of requests for blocks with big number of TXs and unnecessary load on archive nodes. After switching from the custom JS tracer to the `callTracer` it became possible to use `debug_traceBlockByHash` or `debug_traceBlockByNumber` endpoints.
This PR cherry-picks the following upstream commits:
bc30e000f084819717072d66714143a85f96c117 and 4c2c9e32bed801a98a53bc4bfa0851ad761515cf that enable block tracing instead of individual TX tracing for geth.

 ### Other changes

No.

### Tested

Tests included in the commit.
Tested locally with rc1staging env.

### CODE REVIEW

**Comment by rkachowski** [comment]
After deploying `178f8ec` to rc1staging it looks like the ingestion of internal transaction drops significantly 
image
image

indeed i'm not sure it's even indexing internal transactions anymore - the following query returns no records

```sql
select *
from internal_transactions
where transaction_hash in (select hash from public.transactions order by block_number desc limit 1000);
```

**Comment by carterqw2** [comment]
I've updated the blockchain client to match the upstream format in this [PR](https://github.com/celo-org/celo-blockchain/pull/2254), it's already deployed to `rc1staging`. I also updated the blockscout's code to match the previous expectations of having block hashes in internal transaction responses. I tested it locally, seems to be working. @rkachowski could you take another look please?

**Comment by rkachowski** [comment]
Hey @carterqw2 , this requires archive nodes to be deployed at [1fc347330](https://github.com/celo-org/celo-blockchain/commit/1fc34733020cef6666d46ac67c86bfe6e1df2b40) - correct?

**Comment by carterqw2** [comment]
> Hey @carterqw2 , this requires archive nodes to be deployed at [1fc347330](https://github.com/celo-org/celo-blockchain/commit/1fc34733020cef6666d46ac67c86bfe6e1df2b40) - correct?

Yeah, I updated them on `rc1staging` for testing but not on other envs yet.

**Review by jcortejoso — APPROVED** [review]

**Pull request merged**
